spring:
  datasource:
    password: 12345
    url: jdbc:sqlserver://localhost:1433;databaseName=RideOrderingDB;encrypt=false;
    username: sa


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 340216936601-32fpcu5qt29og9leosl8r77bqh4q5t1s.apps.googleusercontent.com
            client-secret: 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
